name: Deploy Go Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t nascript/app-go-kaks-api .
      - name: Push image to docker hub
        run: docker push nascript/app-go-kaks-api:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull nascript/app-go-kaks-api:latest
      - name: Delete old container
        run: docker rm -f app-go-kaks-api-container  
      - name: Run docker container          
        run: docker run -d -p 4040:4040 --name app-go-kaks-api-container nascript/app-go-kaks-api
